### ISSUE TITLE
Better test organization

### ISSUE THREAD

**Issue by lance** [bucharest-gold/automatic-pancake#4]
I think the example project should have two sets of tests that run, unit tests and functional tests. For example:

```
/test/unit/test-a.js
/test/unit/test-b.js
```

and 

```
/test/functional/test-a.js
/test/functional/test-b.js
```

The existing `test-ci.js` could move to `/test/functional/run-tests.js`. The `test` script in package.json could simply be `tape test/unit/*.js` and a new script could be added to either the `Makefile` or `package.json` to run the functional tests. 

By default, when this repo is cloned and a user runs `npm test` probably it should just be the unit tests that are run, with perhaps some console output saying something like "Execute `make ci` to run functional tests.".

Add a `ci` target to the `Makefile` which runs both unit and functional tests, and have `.travis.yml` use `make ci` for the `script` property.

WDYT?

**Comment by helio-frota** [comment]
done.
